# Server configuration
server.port=2001

# PostgreSQL Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/timpdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=timp
spring.datasource.password=timp

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Logging
logging.level.com.timp=INFO
logging.level.org.springframework.web=INFO
logging.level.timp.service.SensorSimulator=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

# JWT configuration
jwt.secret=4hMBUk15seZ4ovnWrvfHOeCOZ69qvn6G29fjXEowh84=
jwt.access-expiration=900000
jwt.refresh-expiration=2592000000

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.imap.host=imap.gmail.com
mail.imap.port=993
mail.imap.ssl.enable=true
mail.imap.auth=true

# SpringDoc / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=list