# Server configuration
server.port=2001

# PostgreSQL Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/timpdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=timp
spring.datasource.password=timp

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Logging
logging.level.com.timp=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.timp.service.SensorSimulator=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

# JWT configuration
jwt.secret=4hMBUk15seZ4ovnWrvfHOeCOZ69qvn6G29fjXEowh84=
jwt.access-expiration=900000
jwt.refresh-expiration=2592000000

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true